### ISSUE TITLE
Feature loan account details

### ISSUE THREAD

**Issue by therajanmaurya** [therajanmaurya/android-client-2.0#38]
**Summary:** 

Implement loan account details feature

<img src="https://user-images.githubusercontent.com/5724482/28035699-3164526e-65d3-11e7-8890-3402e34d64d3.png" width="250" height="450">

**Comment by therajanmaurya** [comment]
Hi @crain, Any feedback

**Comment by crain** [comment]
@therajanmaurya - lgtm. What actions do you plan to use in the context menu in the upper right corner?

**Comment by therajanmaurya** [comment]
For now nothing, I did not implement in mobile UI. I have completed this feature.
